### PR TITLE
Add Ballerina to the Ecosystem section

### PR DESCRIPTION
**Pull request by TharmiganK**
Ballerina is an open source cloud-native programming language optimized for integration. We are excited to share that [Ballerina](https://ballerina.io/), with its flexible, powerful, beautiful integrations as code, is now compatible with the GraalVM's native image compilation feature. This means that now, you can leverage the power of GraalVM to create native executables from the Ballerina applications.

The extensive efforts of the Ballerina ensures a smooth and optimized experience when using Ballerina with GraalVM. This collaboration opens up new possibilities for performance improvements and enhanced developer experiences. Check out our [learn page](https://ballerina.io/learn/graalvm-executable-overview/), our [blog articles](https://medium.com/ballerina-techblog/search?q=graalvm), and the [tech talk](https://www.youtube.com/watch?v=fDRi3rNiFqo) for more information.

We're really looking forward to collaborating with the GraalVM Team to showcase Ballerina's capabilities and contribute to the GraalVM ecosystem. I believe it would be beneficial to both communities to have Ballerina listed as a [supported framework for native image compilation](https://www.graalvm.org/native-image/libraries-and-frameworks/) and list Ballerina as a part of [the Ecosystem page](https://www.graalvm.org/community/opensource/) on the GraalVM website. 

We would greatly appreciate any guidance on the next steps or any additional information you might need from the Ballerina Team. Feel free to suggest any improvements on moving forward with this initiative.

### CODE REVIEW

**Comment by TharmiganK** [comment]
@olyagpl Appreciate your input

**Comment by olyagpl** [comment]
@TharmiganK, thanks for the PR. To add Ballerina to Libs and Frameworks compatible and tested with GraalVM Native Image, you should open a pull request and add an entry to this file: https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list.json according to this https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list-schema.json.

**Comment by TharmiganK** [comment]
> @TharmiganK, thanks for the PR. To add Ballerina to Libs and Frameworks compatible and tested with GraalVM Native Image, you should open a pull request and add an entry to this file: https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list.json according to this scheme: https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list-schema.json.

@olyagpl thanks for the update. But [`Ballerina`](https://ballerina.io/) is not a Java library, it is a language that runs on JVM. Ballerina has its own set of [libraries](https://central.ballerina.io/) which are also GraalVM compatible. 

So we would like to know the possibility of adding Ballerina to `Frameworks Ready for Native Image` section along with the Java Frameworks such as Micronaut, Quarkus and Spring. 

**PS:** Ballerina achieves similar performance compared to the above Java frameworks. Reference: https://medium.com/@ktharmi176/unveiling-ballerina-graalvm-image-a-comparative-analysis-976b07bf3f63

**Comment by TharmiganK** [comment]
@olyagpl Any update on this?

**Comment by olyagpl** [comment]
@TharmiganK, thanks for the clarification. Since [Ballerina](https://ballerina.io/) is a JVM language, and not a library, we can't place it on par with Micronaut, Spring and other Java frameworks. What I believe you should consider is adding Ballerina's set of [libraries](https://central.ballerina.io/) to the compatibility table at https://www.graalvm.org/native-image/libraries-and-frameworks/. The [GraalVM Open Source page](https://github.com/graalvm) outdated and the decision we took was to redirect it to [GraalVM open source project on GitHub](https://github.com/graalvm#graalvm-on-github).

**Comment by TharmiganK** [comment]
@olyagpl Thank you for the response. Adding ballerina's libraries to the compatibility table does not make sense as the libraries are wrote in Ballerina. 

I will close this PR, since the open source page is now changed. Btw I do not see the open source projects list in the GitHub project page. Let us know, if you are listing the open source projects in the GitHub project page, then we can add Ballerina there.

**Pull request closed without merging**
