### PR TITLE
Add RESTHeart to the list of microservices frameworks integrated with GraalVM

### PR DESCRIPTION
**Pull request by ujibang**
We'd love to have RESTHeart added to the list of microservices frameworks integrated with GraalVM.

 RESTHeart fully supports GraalVM:
- can be run with GraalVM's java
- can be built as native image
- allows developing Services and Interceptors in JavaScript when running with GraalVM or using restheart-native (see also https://restheart.org/docs/upgrade-to-v6/#graalvm)

### CODE REVIEW

**Comment by ujibang** [comment]
Contributor agreement signed

**Comment by olyagpl** [comment]
Hi, and this is a great news to hear more frameworks adopting GraalVM! 
We're planning a website redesign soon, Home page will undergo significant changes.  
I think the "Ecosystem" section here https://www.graalvm.org/community/opensource might be a better fit.

**Comment by ujibang** [comment]
Hi @olyagpl 

> I think the "Ecosystem" section here https://www.graalvm.org/community/opensource might be a better fit.

I added RESTHeart to the Ecosystem section of /community/opensource 

ps
My OCA has been processed as well

**Comment by ujibang** [comment]
@olyagpl any news on this PR?

**Comment by olyagpl** [comment]
Hi @ujibang, thanks for your contribution. RESTHeart is listed on our website  https://www.graalvm.org/community/opensource since last week! Sorry for getting back to you just today.

Regards,
Olya

**Comment by olyagpl** [comment]
Closing this PR.

**Comment by ujibang** [comment]
thanks @olyagpl, we didn't notice it!

That's brilliant, we ❤️ GraalVM!

**Pull request closed without merging**
